### ISSUE TITLE
Username and password of web front end gets stored in plain text file AUTHZ

### ISSUE THREAD

**Issue by gsleap** [csiro-rds/casda_vo_tools#11]
Upon setting a new admin password in the .../configure/home web page, a new file, AUTHZ gets created and has the new password (and username) stored in plain text. 

The not so bad part is that the file is only readable by root and users in the root group, however, _surely_ there's a way to just store a one way hash of the password instead?

**Comment by jd-au** [comment]
This has been fixed in the 1.11 release. The password is now stored as a salted hash
