### ISSUE TITLE
ADQL query results containing large integrers are truncated to int32

### ISSUE THREAD

**Issue by gsleap** [csiro-rds/casda_vo_tools#15]
I found this when testing a very simple ADQL query on my TAP service:
"SELECT SUM(access_estsize) as big_number FROM ivoa.obscore"
The result in TOPCAT is "<blank>", the result from pyvo is:
```
<Table length=1>
mwa_big_number
    int32     
--------------
    2147483647
```
The actual result is 34 PB (which in kbytes - as access_est is, ends up being much bigger than the result given. The result given is truncated at the max size of a signed 32 bit integer.

Here is some simple pyvo code to reproduce the issue. I include a query to JVO and CASDA ASKAP TAP which also have the obscore "access_estsize" column - all  (including MWA) defined as BIGINT. Unfortuntely only MWA actually has a value large enough to test this, so I've hacked it my changing the SQL to be SUM(access_estsize) * SUM(access_estsize) in order to produce a value > 2147483647. You can see that JVO, which presumably has their own ADQL/TAP implementation returns a large result, however both CASDA VO Tools examples (MWA, CASDA/ASKAP) truncate at 
2147483647.

```
import pyvo as vo

service1 = vo.dal.TAPService("http://vo.mwatelescope.org:8000/mwa_asvo/tap")
service2 = vo.dal.TAPService("https://casda.csiro.au/casda_vo_tools/tap")
service3 = vo.dal.TAPService("http://jvo.nao.ac.jp/skynode/do/tap/nobeyama/")

resultset1 = service1.search('SELECT SUM(access_estsize)*SUM(access_estsize) as mwa_big_number FROM ivoa.obscore')
resultset2 = service2.search('SELECT SUM(access_estsize)*SUM(access_estsize) as casda_big_number FROM ivoa.obscore')
resultset3 = service3.search('SELECT SUM(access_estsize)*SUM(access_estsize) as jvo_big_number FROM ivoa.obscore')

print(resultset1)
print(resultset2)
print(resultset3)
```
Output:
```
$ python tap_test.py 
<Table length=1>
mwa_big_number
    int32     
--------------
    2147483647

<Table length=1>
casda_big_number
     int32      
----------------
      2147483647

<Table length=1>
  jvo_big_number 
      object     
-----------------
45747978155572900
```

This is tested with CASDA VO Tools 1.8 and 1.11.

**Comment by jd-au** [comment]
We resolved this in v1.13. Calculated numbers are now sent out as char which is handled both by topcat and pyvo.
